baseURL = "https://promhippie.github.io/prometheus-vcd-sd/"
languageCode = "en-us"
title = "Prometheus VMWare vCloud Director SD"
pygmentsUseClasses = true

[markup.goldmark.renderer]
  unsafe = true

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[params]
  author = "Thomas Boerger"
  description = "Prometheus service discovery for VMWare vCloud Director"
  keywords = "prometheus, sd, service, discovery, vcd, vcloud, vmware"
